#include <stdio.h>
#include <stdlib.h>
#include "cda.h"
#include "integer.h"
#include "real.h"
#include "string.h"
extern long random(void);
extern void srandom(unsigned int seed);

int
main(void)
    {
    printf("CDA tester: 3,5\n");
    printf("you can retrieve this test with:\n");
    printf("wget beastie.cs.ua.edu/cs201/testing/0/cda-test-3-5.c\n");
    printf("\noutput:\n\n");
    CDA *d = newCDA(displayINTEGER);
    insertCDAback(d,newINTEGER(404));
    insertCDAback(d,newINTEGER(381));
    insertCDAback(d,newINTEGER(759));
    insertCDAback(d,newINTEGER(181));
    insertCDAback(d,newINTEGER(729));
    insertCDAback(d,newINTEGER(603));
    insertCDAback(d,newINTEGER(304));
    insertCDAback(d,newINTEGER(23));
    insertCDAback(d,newINTEGER(707));
    insertCDAback(d,newINTEGER(606));
    insertCDAback(d,newINTEGER(409));
    insertCDAback(d,newINTEGER(230));
    insertCDAback(d,newINTEGER(347));
    insertCDAback(d,newINTEGER(361));
    insertCDAback(d,newINTEGER(121));
    insertCDAback(d,newINTEGER(34));
    insertCDAback(d,newINTEGER(587));
    insertCDAback(d,newINTEGER(405));
    insertCDAback(d,newINTEGER(24));
    insertCDAback(d,newINTEGER(915));
    insertCDAback(d,newINTEGER(386));
    insertCDAback(d,newINTEGER(400));
    insertCDAback(d,newINTEGER(68));
    insertCDAback(d,newINTEGER(530));
    insertCDAback(d,newINTEGER(983));
    insertCDAback(d,newINTEGER(169));
    insertCDAback(d,newINTEGER(970));
    insertCDAback(d,newINTEGER(751));
    insertCDAback(d,newINTEGER(932));
    insertCDAback(d,newINTEGER(378));
    insertCDAback(d,newINTEGER(768));
    insertCDAback(d,newINTEGER(688));
    insertCDAback(d,newINTEGER(759));
    insertCDAback(d,newINTEGER(879));
    insertCDAback(d,newINTEGER(221));
    insertCDAback(d,newINTEGER(840));
    printf("array d:");
    visualizeCDA(stdout,d);
    printf("\n");
    CDA *e = newCDA(displayINTEGER);
    insertCDAfront(e,newINTEGER(834));
    insertCDAfront(e,newINTEGER(525));
    insertCDAfront(e,newINTEGER(863));
    insertCDAfront(e,newINTEGER(894));
    insertCDAfront(e,newINTEGER(131));
    insertCDAfront(e,newINTEGER(624));
    insertCDAfront(e,newINTEGER(124));
    insertCDAfront(e,newINTEGER(830));
    insertCDAfront(e,newINTEGER(985));
    insertCDAfront(e,newINTEGER(246));
    insertCDAfront(e,newINTEGER(865));
    insertCDAfront(e,newINTEGER(573));
    insertCDAfront(e,newINTEGER(651));
    insertCDAfront(e,newINTEGER(241));
    insertCDAfront(e,newINTEGER(840));
    insertCDAfront(e,newINTEGER(37));
    insertCDAfront(e,newINTEGER(994));
    insertCDAfront(e,newINTEGER(909));
    insertCDAfront(e,newINTEGER(919));
    insertCDAfront(e,newINTEGER(977));
    insertCDAfront(e,newINTEGER(430));
    insertCDAfront(e,newINTEGER(889));
    insertCDAfront(e,newINTEGER(80));
    insertCDAfront(e,newINTEGER(714));
    insertCDAfront(e,newINTEGER(267));
    insertCDAfront(e,newINTEGER(200));
    insertCDAfront(e,newINTEGER(402));
    insertCDAfront(e,newINTEGER(379));
    insertCDAfront(e,newINTEGER(431));
    insertCDAfront(e,newINTEGER(623));
    insertCDAfront(e,newINTEGER(219));
    insertCDAfront(e,newINTEGER(618));
    insertCDAfront(e,newINTEGER(500));
    insertCDAfront(e,newINTEGER(435));
    insertCDAfront(e,newINTEGER(512));
    insertCDAfront(e,newINTEGER(632));
    insertCDAfront(e,newINTEGER(59));
    insertCDAfront(e,newINTEGER(636));
    insertCDAfront(e,newINTEGER(814));
    insertCDAfront(e,newINTEGER(45));
    insertCDAfront(e,newINTEGER(234));
    insertCDAfront(e,newINTEGER(31));
    insertCDAfront(e,newINTEGER(970));
    insertCDAfront(e,newINTEGER(237));
    insertCDAfront(e,newINTEGER(273));
    insertCDAfront(e,newINTEGER(162));
    insertCDAfront(e,newINTEGER(274));
    insertCDAfront(e,newINTEGER(267));
    insertCDAfront(e,newINTEGER(71));
    insertCDAfront(e,newINTEGER(545));
    insertCDAfront(e,newINTEGER(596));
    insertCDAfront(e,newINTEGER(502));
    insertCDAfront(e,newINTEGER(435));
    insertCDAfront(e,newINTEGER(28));
    insertCDAfront(e,newINTEGER(216));
    insertCDAfront(e,newINTEGER(54));
    insertCDAfront(e,newINTEGER(229));
    insertCDAfront(e,newINTEGER(971));
    insertCDAfront(e,newINTEGER(433));
    insertCDAfront(e,newINTEGER(12));
    insertCDAfront(e,newINTEGER(594));
    insertCDAfront(e,newINTEGER(5));
    insertCDAfront(e,newINTEGER(630));
    insertCDAfront(e,newINTEGER(95));
    insertCDAfront(e,newINTEGER(440));
    insertCDAfront(e,newINTEGER(142));
    insertCDAfront(e,newINTEGER(79));
    insertCDAfront(e,newINTEGER(499));
    insertCDAfront(e,newINTEGER(131));
    insertCDAfront(e,newINTEGER(893));
    insertCDAfront(e,newINTEGER(896));
    insertCDAfront(e,newINTEGER(717));
    printf("array e:");
    visualizeCDA(stdout,e);
    printf("\n");
    printf("performing unionCDA(d,e)\n");
    unionCDA(d,e);
    printf("\n");
    printf("array d: ");
    displayCDA(stdout,d);
    printf("\n");
    printf("array e: ");
    displayCDA(stdout,e);
    printf("\n");
    printf("performing unionCDA(d,e)\n");
    unionCDA(d,e);
    printf("\n");
    printf("array d: ");
    displayCDA(stdout,d);
    printf("\n");
    printf("array e: ");
    displayCDA(stdout,e);
    printf("\n");
    printf("performing unionCDA(e,d)\n");
    unionCDA(e,d);
    printf("\n");
    printf("array d: ");
    displayCDA(stdout,d);
    printf("\n");
    printf("array e: ");
    displayCDA(stdout,e);
    printf("\n");
    return 0;
    }
