#include <stdio.h>
#include <stdlib.h>
#include "cda.h"
#include "integer.h"
#include "real.h"
#include "string.h"
extern long random(void);
extern void srandom(unsigned int seed);

int
main(void)
    {
    printf("CDA tester: 1,5\n");
    printf("you can retrieve this test with:\n");
    printf("wget beastie.cs.ua.edu/cs201/testing/0/cda-test-1-5.c\n");
    printf("\noutput:\n\n");
    CDA *d = newCDA(displayINTEGER);
    insertCDAback(d,newINTEGER(383));
    insertCDAback(d,newINTEGER(918));
    insertCDAback(d,newINTEGER(795));
    insertCDAback(d,newINTEGER(466));
    insertCDAback(d,newINTEGER(577));
    insertCDAback(d,newINTEGER(636));
    insertCDAback(d,newINTEGER(182));
    insertCDAback(d,newINTEGER(988));
    insertCDAback(d,newINTEGER(52));
    insertCDAback(d,newINTEGER(471));
    insertCDAback(d,newINTEGER(194));
    insertCDAback(d,newINTEGER(731));
    insertCDAback(d,newINTEGER(26));
    insertCDAback(d,newINTEGER(841));
    insertCDAback(d,newINTEGER(938));
    insertCDAback(d,newINTEGER(472));
    insertCDAback(d,newINTEGER(542));
    insertCDAback(d,newINTEGER(27));
    insertCDAback(d,newINTEGER(232));
    insertCDAback(d,newINTEGER(694));
    insertCDAback(d,newINTEGER(271));
    insertCDAback(d,newINTEGER(959));
    insertCDAback(d,newINTEGER(170));
    insertCDAback(d,newINTEGER(342));
    insertCDAback(d,newINTEGER(524));
    insertCDAback(d,newINTEGER(326));
    insertCDAback(d,newINTEGER(35));
    insertCDAback(d,newINTEGER(310));
    insertCDAback(d,newINTEGER(553));
    printf("array d:");
    visualizeCDA(stdout,d);
    printf("\n");
    CDA *e = newCDA(displayINTEGER);
    insertCDAfront(e,newINTEGER(22));
    insertCDAfront(e,newINTEGER(351));
    insertCDAfront(e,newINTEGER(288));
    insertCDAfront(e,newINTEGER(940));
    insertCDAfront(e,newINTEGER(498));
    insertCDAfront(e,newINTEGER(106));
    insertCDAfront(e,newINTEGER(870));
    insertCDAfront(e,newINTEGER(134));
    insertCDAfront(e,newINTEGER(288));
    insertCDAfront(e,newINTEGER(210));
    insertCDAfront(e,newINTEGER(187));
    insertCDAfront(e,newINTEGER(112));
    insertCDAfront(e,newINTEGER(404));
    insertCDAfront(e,newINTEGER(270));
    insertCDAfront(e,newINTEGER(138));
    insertCDAfront(e,newINTEGER(598));
    insertCDAfront(e,newINTEGER(208));
    insertCDAfront(e,newINTEGER(962));
    insertCDAfront(e,newINTEGER(492));
    insertCDAfront(e,newINTEGER(587));
    insertCDAfront(e,newINTEGER(195));
    insertCDAfront(e,newINTEGER(186));
    insertCDAfront(e,newINTEGER(210));
    insertCDAfront(e,newINTEGER(506));
    insertCDAfront(e,newINTEGER(709));
    insertCDAfront(e,newINTEGER(553));
    insertCDAfront(e,newINTEGER(30));
    insertCDAfront(e,newINTEGER(35));
    insertCDAfront(e,newINTEGER(940));
    insertCDAfront(e,newINTEGER(692));
    insertCDAfront(e,newINTEGER(588));
    insertCDAfront(e,newINTEGER(962));
    insertCDAfront(e,newINTEGER(395));
    insertCDAfront(e,newINTEGER(229));
    insertCDAfront(e,newINTEGER(255));
    insertCDAfront(e,newINTEGER(894));
    insertCDAfront(e,newINTEGER(335));
    insertCDAfront(e,newINTEGER(125));
    insertCDAfront(e,newINTEGER(28));
    insertCDAfront(e,newINTEGER(976));
    insertCDAfront(e,newINTEGER(335));
    insertCDAfront(e,newINTEGER(567));
    insertCDAfront(e,newINTEGER(88));
    insertCDAfront(e,newINTEGER(91));
    insertCDAfront(e,newINTEGER(837));
    insertCDAfront(e,newINTEGER(578));
    insertCDAfront(e,newINTEGER(689));
    insertCDAfront(e,newINTEGER(397));
    insertCDAfront(e,newINTEGER(540));
    insertCDAfront(e,newINTEGER(181));
    insertCDAfront(e,newINTEGER(336));
    insertCDAfront(e,newINTEGER(87));
    insertCDAfront(e,newINTEGER(720));
    insertCDAfront(e,newINTEGER(547));
    insertCDAfront(e,newINTEGER(593));
    insertCDAfront(e,newINTEGER(429));
    insertCDAfront(e,newINTEGER(452));
    insertCDAfront(e,newINTEGER(976));
    printf("array e:");
    visualizeCDA(stdout,e);
    printf("\n");
    printf("performing unionCDA(d,e)\n");
    unionCDA(d,e);
    printf("\n");
    printf("array d: ");
    displayCDA(stdout,d);
    printf("\n");
    printf("array e: ");
    displayCDA(stdout,e);
    printf("\n");
    printf("performing unionCDA(d,e)\n");
    unionCDA(d,e);
    printf("\n");
    printf("array d: ");
    displayCDA(stdout,d);
    printf("\n");
    printf("array e: ");
    displayCDA(stdout,e);
    printf("\n");
    printf("performing unionCDA(e,d)\n");
    unionCDA(e,d);
    printf("\n");
    printf("array d: ");
    displayCDA(stdout,d);
    printf("\n");
    printf("array e: ");
    displayCDA(stdout,e);
    printf("\n");
    return 0;
    }
